# Makefile for Atmos GL Project Suite
.PHONY: run stop build rebuild start-desktop-fg stop-desktop psql logs clean purge backup restore refresh-map test bash status help bootstrap-config migrate

# Variables
DB_USER = agl
DB_PASS = agl
DB_NAME = atmos_gl
DB_SERVICE = atmos_gl_db
DB_PORT = 15432
BUILDER_SERVICE = layer_builder
DUMP_FILE = atmos_gl_dump.sql

export DOCKER_UID := $(shell id -u)
export DOCKER_GID := $(shell id -g)

BACKEND_SERVICES = data_collector layer_builder housekeeper map_api

## reload: Apply CODE changes live — just restart (no rebuild)
reload:
ifndef service
	docker compose restart $(BACKEND_SERVICES)
else
	docker compose restart $(service)
endif

## stop: Bring all containers down
stop:
	docker compose down

## bootstrap-config: Ensure live config/atmos-gl.json, .env, and docker-compose.override.yml exist, and keep atmos-gl.json's shape synced with its template (adds template keys you're missing, drops keys the template no longer defines, never touches the value of anything already there)
# Shared with Makefile.prod via scripts/bootstrap-config.sh (--with-override adds the
# dev-only docker-compose.override.yml step prod has no equivalent of) -- see that
# script's own comment for why this used to live separately in each Makefile.
bootstrap-config:
	@bash scripts/bootstrap-config.sh --with-override

## start|run|up: Start dev stack (auto-merges docker-compose.override.yml)
up run start: bootstrap-config
	docker compose up -d

## build: Rebuild images — only needed for DEPENDENCY changes
build: stop
	docker compose build

## rebuild: Rebuild all images from scratch (no cache)
rebuild:
	docker compose build --no-cache

## prod: Run EXACTLY as a package consumer would
prod: bootstrap-config
	docker compose -f docker-compose.yml pull -q
	docker compose -f docker-compose.yml up -d

## prod-down: Stop the consumer-style stack
prod-down:
	docker compose -f docker-compose.yml down

## logs: Tail all logs; service=name for specific service
logs:
	@bash scripts/logs.sh $(service)

## test: Run all tests (optional: make test include=pattern)
test:
	@echo "Ensuring $(BUILDER_SERVICE) container environment is active..."
	docker compose up $(BUILDER_SERVICE) -d
	@echo "Running complete discovery test suite via pytest..."
	docker compose exec $(BUILDER_SERVICE) uv run pytest tests/ -v $(if $(include),-k $(include))
	@read -p "Remove files generated by testing? [y/N] " ans; \
	if [ "$${ans:-N}" = "y" ] || [ "$${ans:-N}" = "Y" ]; then \
	   docker compose exec $(BUILDER_SERVICE) find ./data -type f -name "test_*" -exec rm {} \; ; \
	fi

## bash: Start a bash session in the main BUILDER_SERVICE app
bash:
	@echo "Ensuring $(BUILDER_SERVICE) container environment is active..."
	docker compose up $(BUILDER_SERVICE) -d
	docker compose exec $(BUILDER_SERVICE) bash

## lint: Run the linter across the code
lint:
	@echo "Ensuring $(BUILDER_SERVICE) container environment is active..."
	docker compose up $(BUILDER_SERVICE) -d
	@echo "Checking for any issues - without fixing"
	docker compose exec $(BUILDER_SERVICE) uv run ruff check src

## lint-format: Run the linter across the code and format to standard
lint-format:
	@echo "Ensuring $(BUILDER_SERVICE) container environment is active..."
	docker compose up $(BUILDER_SERVICE) -d
	@echo "Formatting code to consistent standard"
	docker compose exec $(BUILDER_SERVICE) uv run ruff format src

## lint-fix: Run the linter across the code and fix issues
lint-fix: lint-format
	@echo "Ensuring $(BUILDER_SERVICE) container environment is active..."
	docker compose up $(BUILDER_SERVICE) -d
	@echo "Fixing issues.."
	docker compose exec $(BUILDER_SERVICE) uv run ruff check --fix src

## backup: Backup database to local atmos_gl_dump.sql file
backup:
	@DB_SERVICE=$(DB_SERVICE) DB_USER=$(DB_USER) DB_NAME=$(DB_NAME) DUMP_FILE=$(DUMP_FILE) bash scripts/backup.sh

## restore: Restores the local atmos_gl_dump.sql backup
restore:
	@DB_SERVICE=$(DB_SERVICE) DB_USER=$(DB_USER) DB_NAME=$(DB_NAME) DUMP_FILE=$(DUMP_FILE) BACKEND_SERVICES="$(BACKEND_SERVICES)" bash scripts/restore.sh

## clean: Stop containers, remove images
clean:
	docker compose down --rmi all
	@echo "Containers stopped and project-specific images removed."

## purge: DANGEROUS! Delete all containers, images and data volumes
purge:
	@echo "WARNING: This will delete ALL containers, images, and PERSISTENT DATA volumes."
	@read -p "Are you absolutely sure? [y/N] " ans; \
	if [ "$${ans:-N}" = "y" ] || [ "$${ans:-N}" = "Y" ]; then \
	   docker compose down --rmi all --volumes; \
	   echo "System purged. Database volumes have been deleted."; \
	fi

## psql: Open psql session in map database
psql:
	@DB_SERVICE=$(DB_SERVICE) DB_USER=$(DB_USER) DB_NAME=$(DB_NAME) bash scripts/psql.sh

## migrate: Apply alembic migrations to the local dev database (via uv, outside Docker)
migrate:
	@echo "Ensuring atmos_gl database is running"
	@docker compose up $(DB_SERVICE) -d
	POSTGRES_HOST=localhost POSTGRES_PORT=$(DB_PORT) POSTGRES_USER=$(DB_USER) POSTGRES_PASSWORD=$(DB_PASS) POSTGRES_DB=$(DB_NAME) uv run alembic upgrade head

## status: Database Status Report
status:
	@BUILDER_SERVICE=$(BUILDER_SERVICE) bash scripts/status.sh

## help: Show this help menu
help:
	@echo "Available commands:"
	@sed -n 's/^##//p' $(MAKEFILE_LIST) | awk '{printf "  \033[36m%-20s\033[0m %s\n", $$1, substr($$0, index($$0,$$2))}'
